### ISSUE TITLE
HAOS Invalid Authentication 

### ISSUE THREAD

**Issue by bradarussell** [watkins-matt/home-assistant-google-keep-sync#20]
I'm getting the invalid authentication error with an app password. I'm on HAOS and can't follow the Docker instructions to get a token. Do you know of a workaround or a way to diagnose the issue in HAOS?

**Comment by milkplus27** [comment]
Hi, I'm also struggling with this. Getting an error msg when I try to run the container on two separate Raspberry Pis. So, unable to get a token. Would really love to get this up and running if at all possible.

**Comment by watkins-matt** [comment]
Hi,


The Docker container method is the current accepted workaround for the known authentication issue. 


It doesn't matter whether you are using HAOS or not because you don't run the docker container on the same system that Home Assistant is installed on, it should be on another computer that you install docker on.


I believe the docker image is built for x86 so it won't work with the ARM architecture that Raspberry Pi's use.


If you don't have an extra x86 Linux computer, you can easily install docker on any Windows computer with WSL, see https://learn.microsoft.com/en-us/windows/wsl/install.


Then you would just follow the instructions to install docker https://docs.docker.com/engine/install/ubuntu/.


And finally would follow the instructions in the Readme for the Docker container.

**Comment by milkplus27** [comment]
thanks for this. managed to get it sorted with WSL.
