### ISSUE TITLE
Support for nested lists

### ISSUE THREAD

**Issue by arsenicks** [watkins-matt/home-assistant-google-keep-sync#31]
Hi, first thanks for sharing your work, the setup wasn't flawless as user/password didn't work but the readme/ha-wizard was clear that could happend and generating a token using the suggested container did the trick!

I was wondering if it was possible to support nested item in a list ?
Ex.
List name: Shopping
- Costco
- - X
- - Y
- Pharmacy
- - V

I can't find if this is a limitation on google limiting third party integration or if the lists on ha doesn't allow nested list but that would be awesome if supported!

edit: It looks like it is supported on the google api side: https://developers.google.com/keep/api/reference/rest/v1/notes#listitem ~~so is this a limitation of HA or the integration simply need to get that info ?~~

edit 2: Well the more I dig down the rabbit hole the more I answer myself! It looks like this is a HA limitation according to this post, so I suggest if others are looking for the same feature, go upvote this feature request! https://community.home-assistant.io/t/todo-list-sub-tasks/634919

I'll keep this open for now just in case my research wasn't exact and/or get the input from you guy's!

Thanks again, have a great day!

**Comment by watkins-matt** [comment]
Hi,

I am definitely open to supporting synchronization of the nesting state of list items. As you mentioned, Home Assistant unfortunately doesn't support nested items in lists yet. 

Since this isn't currently possible to implement without changes in Home Assistant, I'm going to close the issue for now. I'd be happy to reopen the issue in the future if changes in Home Assistant make it possible.
