### ISSUE TITLE
Renamed list in Google Keep doesn't sync with HA

### ISSUE THREAD

**Issue by MagnusErler** [watkins-matt/home-assistant-google-keep-sync#35]
Thanks for the HACS integration!

I renamed a list in Google Keep, but the update didn't reflect in HA until I restarted it.

**Comment by watkins-matt** [comment]
Yes, after testing I can confirm I can reproduce this issue. Working on a fix for it.

**Comment by watkins-matt** [comment]
This should be fixed in the latest beta https://github.com/watkins-matt/home-assistant-google-keep-sync/releases/tag/0.9.9b2. Everything seems to work as expected from my limited testing. 

If a list is renamed or deleted it will update on the next sync interval (within 15 minutes or when the service is called). Note that a list will only be deleted in Home Assistant when it's removed from the trash in Google Keep; just putting it in the trash without emptying the trash will not delete it in the integration.
