### ISSUE TITLE
Getting "Integration is already configured for this user." error message event though I haven't set it up

### ISSUE THREAD

**Issue by MajorQuake18** [watkins-matt/home-assistant-google-keep-sync#37]
I am getting the error message "Integration is already configured for this user." even though I've never set up this integration. I had to try to add this integration using the token as the password method didn't work for me.

**Comment by watkins-matt** [comment]
Hi, this is a known issue with the current version and is fixed in the latest beta release. Prior issue here: https://github.com/watkins-matt/home-assistant-google-keep-sync/issues/34

It should be fixed if you update to the latest beta version. Password authentication does not work most of the time due to underlying library issues (not fixable by me directly) and using a token is always the preferred method.

**Comment by MajorQuake18** [comment]
That worked, thanks!
